cat aggregation.graphqls >> all.graphql
cat alarm.graphqls >> all.graphql
cat alarm-extend.graphqls >> all.graphql
cat call.graphqls >> all.graphql
cat common.graphqls >> all.graphql
cat log.graphqls >> all.graphql
cat metadata.graphqls >> all.graphql
cat metric.graphqls >> all.graphql
cat metric-extend.graphqls >> all.graphql
cat service-inventory-mapping.graphqls >> all.graphql
cat top-n-records.graphqls >> all.graphql
cat topology.graphqls >> all.graphql
cat topology-extend.graphqls >> all.graphql
cat trace.graphqls >> all.graphql
